### ISSUE TITLE
Suggestion - Show Updates as Releases

### ISSUE THREAD

**Issue by joel72265** [loganmarchione/docker-postfixrelay#51]
This a suggestion, so users can see you are actively updating the project.

On the project page, I noticed that when the source code is updated or whatever it does not show on the project page (screenshot attached). 
![postfix09](https://github.com/user-attachments/assets/98095168-7531-49e9-8fcf-d5f0c0286235)

**Comment by loganmarchione** [comment]
I appreciate the suggestions, but I don't use GitHub-specific features unless I really need them. 

**Releases/tags**

On most of my projects, I use `tags` instead of GitHub's `releases`. The `tags` section isn't as pretty as `releases`, but it's standard `git` stuff, and will work on any other platform if I migrate (GitLab, SourceHut, etc...).  On this project, you can see the tags [here](https://github.com/loganmarchione/docker-postfixrelay/tags).

**Packages**

I also prefer publishing my containers to DockerHub (again, I don't want to rely too much on GitHub). On this project, you can see the container tags [here](https://hub.docker.com/r/loganmarchione/docker-postfixrelay).

**Comment by joel72265** [comment]
yes, I noticed the tags. You know what works for you and the connected systems
