### ISSUE TITLE
587

### ISSUE THREAD

**Issue by hkechung** [loganmarchione/docker-postfixrelay#56]
regarding TLS support for SMTPD and listen on 587 ? 
Can we just change to 587:587 and work ? or need to do something specific ?

**Comment by loganmarchione** [comment]
Hey there 👋 This container does not support TLS on SMTPD and I don't plan on adding it.

FYI, you can't just change the ports, because port 25 is hard-coded into the [Dockerfile](https://github.com/loganmarchione/docker-postfixrelay/blob/master/Dockerfile#L21) and the only [SSL/TLS settings](https://github.com/loganmarchione/docker-postfixrelay/blob/master/entrypoint.sh#L70) are for connecting to a SSL/TLS server (e.g., Gmail, AWS SES, etc...).

I was considering adding TLS support, but the added overhead of TLS certificate management isn't worth it to me. There are too many configuration options that aren't worth it to me:

- Do I use the default snakeoil certs?
- Do I let a user pass certs in with a Docker volume?
- Do I generate certs inside the container?
- How do you renew the certs?
- What algorithm should the certs use?
- What should the key size be?
- Will all clients accept the certs?

I do enforce connecting to a SMTP server (e.g., Gmail, AWS SES, etc...) over TLS. This container is meant to be run on a TRUSTED internal network, where it relays emails via TLS to a SMTP server.
